### PR TITLE
Show validation message when language is not picked for an invitation

### LINKED ISSUE #412: Add missing validation message when language is not picked for an invitation

### PR DESCRIPTION
**Pull request by amos-kibet**
Resolves #412 & #421.

https://github.com/user-attachments/assets/fc5b48ef-4ed2-4c9c-abfe-a67b9a8c9164

I haven't figured [this](https://github.com/3Stones-io/omedis/issues/412#issuecomment-2513460693) out yet. 
Or, is the validation for the radio button supposed to be shown when other form fields are selected? I expect it to only be shown when one tries to submit the form without selecting the language.

The issue above has been fixed, see here:

https://github.com/user-attachments/assets/c374dbd1-b996-4306-9025-d051bc3bbb0e

### CODE REVIEW

**Comment by almirsarajcic** [comment]
We shouldn't look at the code together anymore.
One look and we got 2-3 new tasks...

**Comment by amos-kibet** [comment]
I forgot about [this](https://github.com/3Stones-io/omedis/issues/412#issuecomment-2517070788) comment :D

**Comment by almirsarajcic** [comment]
Good thing you noted it. We might have both forgotten :D

**Comment by amos-kibet** [comment]
We now prefill the form with the current user's language:

https://github.com/user-attachments/assets/cf3a7172-948a-4838-86c6-7c22d982bb0d

**Review by almirsarajcic — APPROVED** [review]

**Comment by almirsarajcic** [comment]
This will be shown if some user somehow unchecks the language (I don't think it's possible without playing around with JS/console.
Screenshot 2024-12-05 at 12 56 16

**Pull request merged**
